# Generated by Django 4.0.3 on 2022-03-16 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_book_contacts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=phone_book_contacts.models.set_name_and_folder_excel_file)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('tel_work', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('tel_home', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('comment', models.TextField(blank=True, default='', max_length=1000, null=True)),
                ('is_public', models.CharField(default='خیر', max_length=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
