# Generated by Django 4.0.2 on 2022-02-23 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phone_book_contacts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='num_company_or_home',
        ),
    ]
