# Generated by Django 4.0.2 on 2022-02-27 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_book_contacts.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('phone_book_contacts', '0002_remove_contact_num_company_or_home'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=phone_book_contacts.models.set_name_and_folder_excel_file)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
